### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by usernameoremail** [ForestwoodMS/forestwoodms.github.io#3]
I believe that the page could do better if their is a gape between the menu and the calendar, so the calendar is at its best.

**Comment by awesomebing1** [comment]
I think we need to edit the x-index (or whatever it is) to make the menu be ontop of the calendar. Let me work on that.

**Comment by usernameoremail** [comment]
just remember the garden ridge PTA is the example that is set for us, make sure its like the garden ridge website, at least somewhat.
